### ISSUE TITLE
MM60 Matl Update: why SQL so slow??????

### ISSUE THREAD

**Issue by calvinc460** [calvinc-org-10/WICS-3#60]

**Comment by curtindolph-calvin-10** [comment]
This will be open for a while.  As of today (2023-05-28), the MM60 update runs reasonably fast in DEV, but times out in PROD (the code continues to run after the web page crashed, and even runs to completion; it just doesn't show results because there is no web page to redirect to.

My plan at the moment is to learn how to do the deletes and adds to MaterialList asynchronously and let the web page know the results when done.  This will take a while to learn.

**Comment by calvinc460** [comment]
commit 7626139 seemed to do the trick.
